import os
import random

from openai import OpenAI
from utils import File, Log, Time, TimeFormat

from digest.article import Article

log = Log("NewsDigest")


class NewsDigest:
    DIGEST_PATH = "README.md"
    MAX_CONTENT_LEN = 320_000
    MODEL = "gpt-5"

    @staticmethod
    def get_news_article_content() -> str:
        articles = Article.list_all()
        content = ""
        used_articles = []
        total_len = 0
        for article in articles:
            total_len += len(article.all_text) + 3
            used_articles.append(article)
            if total_len > NewsDigest.MAX_CONTENT_LEN:
                break
        random.shuffle(used_articles)
        content = "\n...\n".join([a.all_text for a in used_articles])
        used_articles.sort(key=lambda a: a.time_ut, reverse=True)
        return content, used_articles

    def __init__(self):
        self.news_article_content, self.used_articles = (
            self.get_news_article_content()
        )

    @property
    def lines_digest(self) -> list[str]:
        client = OpenAI()
        response = client.responses.create(
            model=self.MODEL,
            reasoning={"effort": "low"},
            max_output_tokens=1_500,
            input=[
                {
                    "role": "system",
                    "content": File(
                        os.path.join("prompts", "digest.txt")
                    ).read(),
                },
                {
                    "role": "user",
                    "content": self.news_article_content,
                },
            ],
        )

        return [response.output_text, ""]

    @property
    def lines_used_articles(self) -> list[str]:
        lines = ["## Articles used", ""]
        for i, article in enumerate(self.used_articles, start=1):
            lines.append(
                f"{i}. `{article.date_str}` {article.description}"
                + f" [{article.newspaper_id}]({article.url_metadata})"
            )
        lines.append("")
        return lines

    @property
    def lines_summary(self) -> list[str]:
        n = len(self.used_articles)
        date_strs = [a.date_str for a in self.used_articles]
        min_date_str = min(date_strs)
        max_date_str = max(date_strs)
        return [
            f"*Generated by {self.MODEL} from {n:,} English News Articles"
            + f" between {min_date_str} and {max_date_str}.*",
            "",
        ]

    @property
    def lines(self) -> list[str]:
        time_str = TimeFormat.TIME.format(Time.now())
        return (
            [f"# News Digest - {time_str}", ""]
            + self.lines_summary
            + self.lines_digest
            + self.lines_used_articles
        )

    def build(self):
        digest_file = File(self.DIGEST_PATH)
        digest_file.write("\n".join(self.lines))
        log.info(f"Built {digest_file}")
