import os

from utils import File, Format, Log, Time, TimeFormat

log = Log("NewsDigest")


class NewsDigestReadMeMixin:
    DIR_DATA_README_HISTORY = os.path.join("data", "readme_history")
    DIGEST_PATH = "README.md"
    MODEL_URL = "https://platform.openai.com/docs/models/gpt-5"
    URL_HISTORY = (
        "https://github.com"
        + "/nuuuwan/lk_news_digest"
        + "/tree/main/data/readme_history"
    )

    @property
    def lines_digest(self) -> list[str]:
        digest_data = self.get_digest_data()
        for item in digest_data:
            title = item["title"]
            body = item["body"]
            self.lines.extend(
                [
                    f"## {title}",
                    "",
                    body,
                    "",
                ]
            )

        return [
            "---",
            "",
            f"[Previous Editions]({self.URL_HISTORY})",
            "",
        ]

    @property
    def lines_used_articles(self) -> list[str]:
        lines = ["## References", ""]
        for i, article in enumerate(self.used_articles, start=1):
            lines.append(
                f"{i}. `{article.date_str}` {article.description}"
                + f" [{article.newspaper_id}]({article.url_metadata})"
            )
        lines.append("")
        return lines

    @property
    def lines_summary(self) -> list[str]:
        time_updated = TimeFormat.TIME.format(Time.now())
        n = len(self.used_articles)
        date_strs = [a.date_str for a in self.used_articles]
        min_date_str = min(date_strs)
        max_date_str = max(date_strs)
        time_updated_for_badge = Format.badge(time_updated)

        return [
            "![LastUpdated](https://img.shields.io/badge"
            + f"/last_updated-{time_updated_for_badge}-green)",
            "",
            f"*Generated by [{self.MODEL}]({self.MODEL_URL})"
            + f" from **{n:,}** English News Articles published"
            + f" between **{min_date_str}** & **{max_date_str}**.*",
            "",
        ]

    @property
    def lines_model_details(self) -> list[str]:
        return [
            f"## Model Prompt (for [{self.MODEL}]({self.MODEL_URL}))",
            "",
            "```",
            self.system_prompt,
            "```",
            "",
        ]

    @property
    def lines_footer(self) -> list[str]:
        return [
            "![Maintainer]"
            + "(https://img.shields.io/badge/maintainer-nuuuwan-red)",
            "![MadeWith](https://img.shields.io/badge/made_with-python-blue)",
            "[![License: MIT]"
            + "(https://img.shields.io/badge/License-MIT-yellow.svg)]"
            + "(https://opensource.org/licenses/MIT)",
            "",
        ]

    @property
    def lines(self) -> list[str]:

        return (
            ["# 🇱🇰 Sri Lanka This Week", ""]
            + self.lines_summary
            + self.lines_digest
            + self.lines_used_articles
            + self.lines_model_details
            + self.lines_footer
        )

    def __save_copy_to_history__(self, content: str):
        ts = TimeFormat.TIME_ID.format(Time.now())
        os.makedirs(self.DIR_DATA_README_HISTORY, exist_ok=True)
        history_digest_path = os.path.join(
            self.DIR_DATA_README_HISTORY, self.DIGEST_PATH[:-3] + f".{ts}.md"
        )
        history_digest_file = File(history_digest_path)
        history_digest_file.write(content)
        log.info(f"Wrote {history_digest_file}")

    def build_readme(self):
        content = "\n".join(self.lines)
        digest_file = File(self.DIGEST_PATH)
        digest_file.write(content)
        log.info(f"Wrote {digest_file}")

        self.__save_copy_to_history__(content)
