import os

from utils import File, Format, Log, Time, TimeFormat

log = Log("NewsDigest")


class NewsDigestReadMeMixin:
    DIR_DATA_README_HISTORY = os.path.join("data", "readme_history")
    DIGEST_PATH = "README.md"
    MODEL_URL = "https://platform.openai.com/docs/models/gpt-5"
    URL_HISTORY = (
        "https://github.com"
        + "/nuuuwan/lk_news_digest"
        + "/tree/main/data/readme_history"
    )

    def get_lines_digest(self) -> list[str]:
        digest_article_list = self.get_digest_article_list()
        log.debug(f"Digest has {len(digest_article_list)} articles.")

        lines = []
        for digest_article in digest_article_list:
            title = digest_article["title"]
            body = digest_article["body"]
            lines.extend(
                [
                    f"## {title}",
                    "",
                    body,
                    "",
                ]
            )

        lines.extend(
            [
                "---",
                "",
                f"[Previous Editions]({self.URL_HISTORY})",
                "",
            ]
        )
        return lines

    def get_lines_used_articles(self) -> list[str]:
        lines = ["## References", ""]
        for i, article in enumerate(self.used_articles, start=1):
            lines.append(
                f"{i}. `{article.date_str}` {article.description}"
                + f" [{article.newspaper_id}]({article.url_metadata})"
            )
        lines.append("")
        return lines

    def get_lines_header(self) -> list[str]:
        time_updated = TimeFormat.TIME.format(Time.now())
        n = len(self.used_articles)
        date_strs = [a.date_str for a in self.used_articles]
        min_date_str = min(date_strs)
        max_date_str = max(date_strs)
        time_updated_for_badge = Format.badge(time_updated)

        return [
            "# 🇱🇰 Sri Lanka This Week",
            "",
            "![LastUpdated](https://img.shields.io/badge"
            + f"/last_updated-{time_updated_for_badge}-green)",
            "",
            f"*Generated by [{self.MODEL}]({self.MODEL_URL})"
            + f" from **{n:,}** English News Articles published"
            + f" between **{min_date_str}** & **{max_date_str}**.*",
            "",
        ]

    def get_lines_model_details(self) -> list[str]:
        return [
            f"## Model Prompt (for [{self.MODEL}]({self.MODEL_URL}))",
            "",
            "```",
            self.system_prompt,
            "```",
            "",
        ]

    def get_lines_footer(self) -> list[str]:
        return [
            "![Maintainer]"
            + "(https://img.shields.io/badge/maintainer-nuuuwan-red)",
            "![MadeWith](https://img.shields.io/badge/made_with-python-blue)",
            "[![License: MIT]"
            + "(https://img.shields.io/badge/License-MIT-yellow.svg)]"
            + "(https://opensource.org/licenses/MIT)",
            "",
        ]

    def get_lines(self) -> list[str]:
        return (
            self.get_lines_header()
            + self.get_lines_digest()
            + self.get_lines_used_articles()
            + self.get_lines_model_details()
            + self.get_lines_footer()
        )

    def __save_copy_to_history__(self, content: str):
        os.makedirs(self.DIR_DATA_README_HISTORY, exist_ok=True)
        history_digest_path = os.path.join(
            self.DIR_DATA_README_HISTORY,
            self.DIGEST_PATH[:-3] + f".{self.ts}.md",
        )
        history_digest_file = File(history_digest_path)
        history_digest_file.write(content)
        log.info(f"Wrote {history_digest_file}")

    def build_readme(self):
        content = "\n".join(self.get_lines())
        digest_file = File(self.DIGEST_PATH)
        digest_file.write(content)
        log.info(f"Wrote {digest_file}")

        self.__save_copy_to_history__(content)
